apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-operatorgroup.yaml
  - 01-subscription-logging.yaml
  - 02-subscription-loki.yaml
  - 20-lokistack.yaml
  - 30-clusterlogforwarder.yaml
