apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ldap-ocp-cluster-admins
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ocp-cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
